### ISSUE TITLE
Example not working with github dependency

### ISSUE THREAD

**Issue by ibogolyubskiy** [shehabic/sherlock#2]
Clone repo, go to app's build.gradle and replace project dependencies to github artifacts (like in readme):
<pre><code>debugImplementation project(':sherlock')
releaseImplementation project(':sherlock-no-op')</code></pre>
to
<pre><code>debugImplementation 'com.github.shehabic.sherlock:sherlock:v0.10.5'
releaseImplementation 'com.github.shehabic.sherlock:sherlock-no-op:v0.10.5'</code></pre>

add jitpack repository to root build.gradle like in readme
<pre><code>maven { url 'https://jitpack.io' }</code></pre>
Sync project and run it.
After launch application crashes with this exception:
<pre><code>java.lang.NoClassDefFoundError: com.shehabic.sherlock.db.Db
 at com.shehabic.sherlock.NetworkSherlock.getDb(NetworkSherlock.kt:173)
 at com.shehabic.sherlock.NetworkSherlock.access$getDb(NetworkSherlock.kt:26)
 at com.shehabic.sherlock.NetworkSherlock$startSession$1.run(NetworkSherlock.kt:185)
 at android.os.Handler.handleCallback(Handler.java:742)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:157)
 at android.os.HandlerThread.run(HandlerThread.java:61)</code></pre>

**Comment by ibogolyubskiy** [comment]
adding 

>     implementation "android.arch.persistence.room:runtime:$architecture_version"
    kapt "android.arch.persistence.room:compiler:$architecture_version"

fixes it

**Comment by ibogolyubskiy** [comment]
`    implementation "android.arch.persistence.room:runtime:$architecture_version"
    kapt "android.arch.persistence.room:compiler:$architecture_version"`

adding these lines to app's build.gradle fixes it

**Comment by ibogolyubskiy** [comment]
<pre><code>implementation "android.arch.persistence.room:runtime:$architecture_version"
kapt "android.arch.persistence.room:compiler:$architecture_version"</code></pre>

adding these lines to app's build.gradle fixes it

**Comment by shehabic** [comment]
Thanks for reporting I'll try to look for a solution for it.
